import type { Product } from "../shared/types.js";

// A small apparel showroom. One of each item is on the floor; everything else
// lives in the stockroom and is pulled on request by staff.
const PRODUCTS: Product[] = [
  {
    id: "p-linen-shirt",
    tagCode: "1001",
    name: "Linen Camp Shirt",
    brand: "Atlas & Oak",
    category: "Tops",
    garment: "tshirt",
    price: 68,
    description: "Breathable washed linen with a relaxed camp collar.",
    colors: [
      { name: "Sand", hex: "#d8c5a5" },
      { name: "Sage", hex: "#9aa886" },
      { name: "White", hex: "#f4f1ea" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "p-merino-tee",
    tagCode: "1002",
    name: "Merino Crew Tee",
    brand: "Atlas & Oak",
    category: "Tops",
    garment: "tshirt",
    price: 54,
    description: "Featherweight merino that breathes and never clings.",
    colors: [
      { name: "Black", hex: "#222222" },
      { name: "Heather Grey", hex: "#9b9b9b" },
      { name: "Navy", hex: "#27374d" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "p-wrap-dress",
    tagCode: "1003",
    name: "Silk Wrap Dress",
    brand: "Marguerite",
    category: "Dresses",
    garment: "dress",
    price: 148,
    description: "A bias-cut wrap dress in fluid washable silk.",
    colors: [
      { name: "Crimson", hex: "#a3263a" },
      { name: "Ink", hex: "#1f2233" },
      { name: "Emerald", hex: "#1f5f4d" },
    ],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "p-slip-dress",
    tagCode: "1004",
    name: "Satin Slip Dress",
    brand: "Marguerite",
    category: "Dresses",
    garment: "dress",
    price: 112,
    description: "Minimalist cowl-neck slip with adjustable straps.",
    colors: [
      { name: "Champagne", hex: "#e7d3b0" },
      { name: "Charcoal", hex: "#3a3a3a" },
    ],
    sizes: ["XS", "S", "M", "L"],
  },
  {
    id: "p-tapered-chino",
    tagCode: "1005",
    name: "Tapered Chino",
    brand: "Northbound",
    category: "Bottoms",
    garment: "pants",
    price: 88,
    description: "Stretch-cotton chino with a clean tapered leg.",
    colors: [
      { name: "Stone", hex: "#c8b89a" },
      { name: "Olive", hex: "#6b6f47" },
      { name: "Navy", hex: "#27374d" },
    ],
    sizes: ["28", "30", "32", "34", "36"],
  },
  {
    id: "p-wide-jean",
    tagCode: "1006",
    name: "Wide-Leg Jean",
    brand: "Northbound",
    category: "Bottoms",
    garment: "pants",
    price: 98,
    description: "Rigid organic denim with a high rise and wide leg.",
    colors: [
      { name: "Indigo", hex: "#33415c" },
      { name: "Ecru", hex: "#e3ddcf" },
    ],
    sizes: ["24", "26", "28", "30", "32"],
  },
  {
    id: "p-field-jacket",
    tagCode: "1007",
    name: "Field Jacket",
    brand: "Northbound",
    category: "Outerwear",
    garment: "jacket",
    price: 178,
    description: "Water-repellent waxed cotton with a four-pocket front.",
    colors: [
      { name: "Olive", hex: "#5d6240" },
      { name: "Black", hex: "#222222" },
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "p-wool-coat",
    tagCode: "1008",
    name: "Wool Overcoat",
    brand: "Atlas & Oak",
    category: "Outerwear",
    garment: "jacket",
    price: 264,
    description: "Double-faced Italian wool with a relaxed drop shoulder.",
    colors: [
      { name: "Camel", hex: "#c19a6b" },
      { name: "Charcoal", hex: "#3a3a3a" },
    ],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "p-leather-sneaker",
    tagCode: "1009",
    name: "Leather Court Sneaker",
    brand: "Pace",
    category: "Footwear",
    garment: "shoes",
    price: 124,
    description: "Minimal full-grain leather sneaker on a cup sole.",
    colors: [
      { name: "White", hex: "#f4f1ea" },
      { name: "Black", hex: "#222222" },
    ],
    sizes: ["7", "8", "9", "10", "11", "12"],
  },
  {
    id: "p-chelsea-boot",
    tagCode: "1010",
    name: "Suede Chelsea Boot",
    brand: "Pace",
    category: "Footwear",
    garment: "shoes",
    price: 188,
    description: "Italian suede Chelsea boot with elastic side gores.",
    colors: [
      { name: "Tobacco", hex: "#7c5234" },
      { name: "Stone", hex: "#b6a98f" },
    ],
    sizes: ["7", "8", "9", "10", "11"],
  },
  {
    id: "p-cashmere-scarf",
    tagCode: "1011",
    name: "Cashmere Scarf",
    brand: "Marguerite",
    category: "Accessories",
    garment: "accessory",
    price: 76,
    description: "Lofty brushed cashmere in a generous wrap size.",
    colors: [
      { name: "Oatmeal", hex: "#d9cdb8" },
      { name: "Plum", hex: "#5e3a52" },
      { name: "Forest", hex: "#33503f" },
    ],
    sizes: ["One Size"],
  },
  {
    id: "p-leather-belt",
    tagCode: "1012",
    name: "Bridle Leather Belt",
    brand: "Pace",
    category: "Accessories",
    garment: "accessory",
    price: 58,
    description: "Vegetable-tanned bridle leather with a brass buckle.",
    colors: [
      { name: "Tan", hex: "#9c6b3f" },
      { name: "Black", hex: "#222222" },
    ],
    sizes: ["S", "M", "L"],
  },
];

// Attach the hero photo for each product. Files live in /public/products and
// are named after the product id with the "p-" prefix dropped.
export const CATALOG: Product[] = PRODUCTS.map((p) => ({
  ...p,
  image: `/products/${p.id.replace(/^p-/, "")}.jpg`,
}));
